/**:
  ros__parameters:
    motions:
      start_arm: 
        joints: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint]
        times_from_start: [0.0, 5.0]
        positions: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
                    -1.57, -0.9, 0.0, 0.65, 0.0, -1.20, 1.57]
        meta:
          name: Start arm
          usage: demo
          description: Start position arm
      
      first_motion: 
        joints: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint]
        times_from_start: [0.0, 5.0]
        positions: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
                    -0.062832, -0.635944, -3.14, -1.621959, 3.141, 0.831, 0.0174] 
        meta:
          name: First motion
          usage: demo
          description: First motion arm