#!/usr/bin/env python3

# Copyright (c) 2024 PAL Robotics S.L. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


import em
import sys
import os


em_file_path = sys.argv[1]

no_em_extension_path = os.path.splitext(em_file_path)[0]
no_extension_path = os.path.splitext(no_em_extension_path)[0]
extension = os.path.splitext(no_em_extension_path)[1]

end_effectors = ["pal-pro-gripper", "custom", "no-ee"]
ft_sensors = ["rokubi", None]
for end_effector in end_effectors:
    for ft_sensor in ft_sensors:
        cfg = {
            "end_effector": end_effector,
            "ft_sensor": ft_sensor,
        }
        with open(em_file_path, "r") as f:
            expanded_contents = em.expand(f.read(), cfg)
        if ft_sensor is None:
            suffix = "_{}".format(end_effector)
        else:
            suffix = "_{}_{}".format(end_effector, ft_sensor)
        expanded_file_name = no_extension_path + suffix + extension
        with open(expanded_file_name, "w") as f:
            msg = "Autogenerated file, don't edit this, edit {} instead".format(
                os.path.basename(em_file_path))
            if extension == ".yaml":
                f.write("#" + msg + "\n")
            # If we add a comment at the begining of an xml the format is not correct.
            # elif extension in [".xacro", ".xml", ".srdf"]:
            #    f.write("<!-- " + msg + "-->\n")

            f.write(expanded_contents)
        print("Generated " + expanded_file_name)
