${FT_SIDE_PREFIX}_controller:
  ros__parameters:
    type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster
    frame_id: ${LINK_SIDE_PREFIX}_ft_sensor_link
    sensor_name: ${LINK_SIDE_PREFIX}_ft_sensor
